In [3]:
import numpy as np

In [ ]:
#arthmetic operations on 1D array

In [15]:
#addition
arr1=np.array([1,22,3,3,4,212])
arr2=np.array([2,33,4,55,6,777])
print(arr1+arr2)
np.add(arr1,arr2)

[  3  55   7  58  10 989]


array([  3,  55,   7,  58,  10, 989])

In [21]:
#suntraction
arr1=np.array([2,33,4,55,6,777])
arr2=np.array([1,22,3,3,4,212])
print(arr1-arr2)
np.subtract(arr2,arr1)

[  1  11   1  52   2 565]


array([  -1,  -11,   -1,  -52,   -2, -565])

In [23]:
#multiplication
arr1=np.array([2,3,4,56,6])
n=3
arr2=np.array([2,33,4,5,6])
print(arr1*arr2)
print(arr1*n)
print(n*arr2)
print(np.multiply(arr1,arr2))

[  4  99  16 280  36]
[  6   9  12 168  18]
[ 6 99 12 15 18]
[  4  99  16 280  36]


In [25]:
#division
arr1=np.array([22,33,44,56,66])
n=3
arr2=np.array([2,33,4,5,6])
print(arr1/arr2)
print(arr1/n)
print(n/arr2)
print(np.divide(arr1,arr2))

[11.   1.  11.  11.2 11. ]
[ 7.33333333 11.         14.66666667 18.66666667 22.        ]
[1.5        0.09090909 0.75       0.6        0.5       ]
[11.   1.  11.  11.2 11. ]


In [29]:
#floor division
arr1=np.array([22,33,44,56,66])
n=3
arr2=np.array([2,33,4,5,6])
print(arr1//arr2)
print(arr1//n)
print(n//arr2)
print(np.floor_divide(arr1,arr2))

[11  1 11 11 11]
[ 7 11 14 18 22]
[1 0 0 0 0]
[11  1 11 11 11]


In [37]:
#modulus
arr1=np.array([1,22,3,4,5])
n=3
arr2=np.array([2,4,5,6,6])
print(arr1%arr2)
print(arr1%n)
print(n%arr2)
print(np.mod(arr1,arr2))

[1 2 3 4 5]
[1 1 0 1 2]
[1 3 3 3 3]
[1 2 3 4 5]


In [51]:
#square root
arr1=np.array([66,677,83,91,93])
arr2=np.array([4,5,7,8,2])
print(np.sqrt(arr1))
print(np.sqrt(arr2))

[ 8.1240384  26.01922366  9.11043358  9.53939201  9.64365076]
[2.         2.23606798 2.64575131 2.82842712 1.41421356]


In [ ]:
#arthmetic operations on 2D array

In [55]:
#addition
arr1=np.array([[1,22,3,3,4,212],[2,2,3,5,7,8]])
arr2=np.array([[2,33,4,55,6,777],[73,2,3,4,5,66]])
print(arr1+arr2)
np.add(arr1,arr2)

[[  3  55   7  58  10 989]
 [ 75   4   6   9  12  74]]


array([[  3,  55,   7,  58,  10, 989],
       [ 75,   4,   6,   9,  12,  74]])

In [59]:
#suntraction
arr1=np.array([[2,33,4,55,6,777],[32,3,4,5,56,6]])
arr2=np.array([[1,22,3,3,4,212],[3,434,4,44,44,3]])
print(arr1-arr2)
np.subtract(arr2,arr1)

[[   1   11    1   52    2  565]
 [  29 -431    0  -39   12    3]]


array([[  -1,  -11,   -1,  -52,   -2, -565],
       [ -29,  431,    0,   39,  -12,   -3]])

In [63]:
#multiplication
arr1=np.array([[2,3,4,56,6],[23,4,5,2,4]])
n=4
arr2=np.array([[2,33,4,5,6],[2,23,5,0,5]])
print(arr1*arr2)
print(arr1*n)
print(n*arr2)
print(np.multiply(arr1,arr2))

[[  4  99  16 280  36]
 [ 46  92  25   0  20]]
[[  8  12  16 224  24]
 [ 92  16  20   8  16]]
[[  8 132  16  20  24]
 [  8  92  20   0  20]]
[[  4  99  16 280  36]
 [ 46  92  25   0  20]]


In [65]:
#division
arr1=np.array([[22,33,44,56,66],[8,3,1,2,22]])
arr2=np.array([[2,33,4,5,6],[73,2,3,4,5]])
n=10
print(arr1/arr2)
print(arr1/n)
print(n/arr2)
print(np.divide(arr1,arr2))

[[11.          1.         11.         11.2        11.        ]
 [ 0.10958904  1.5         0.33333333  0.5         4.4       ]]
[[2.2 3.3 4.4 5.6 6.6]
 [0.8 0.3 0.1 0.2 2.2]]
[[5.         0.3030303  2.5        2.         1.66666667]
 [0.1369863  5.         3.33333333 2.5        2.        ]]
[[11.          1.         11.         11.2        11.        ]
 [ 0.10958904  1.5         0.33333333  0.5         4.4       ]]


In [69]:
#floor division
arr1=np.array([[22,33,44,56,66],[23,4,55,7,30]])
arr2=np.array([[2,33,4,5,6],[3,1,1,3,5]])
n=11
print(arr1//arr2)
print(arr1//n)
print(n//arr2)
print(np.floor_divide(arr1,arr2))

[[11  1 11 11 11]
 [ 7  4 55  2  6]]
[[2 3 4 5 6]
 [2 0 5 0 2]]
[[ 5  0  2  2  1]
 [ 3 11 11  3  2]]
[[11  1 11 11 11]
 [ 7  4 55  2  6]]


In [71]:
#modulus
arr1=np.array([[1,22,3,4,5],[6,3,2,3,4]])
arr2=np.array([[2,4,5,6,6],[3,2,4,6,77]])
n=6
print(arr1%arr2)
print(arr1%n)
print(n%arr2)
print(np.mod(arr1,arr2))

[[1 2 3 4 5]
 [0 1 2 3 4]]
[[1 4 3 4 5]
 [0 3 2 3 4]]
[[0 2 1 0 0]
 [0 0 2 0 6]]
[[1 2 3 4 5]
 [0 1 2 3 4]]


In [73]:
#square root
arr1=np.array([[66,677,83,91,93],[3,222,34,66,2]])
arr2=np.array([[4,5,7,8,2],[22,35,66,44,23]])
print(np.sqrt(arr1))
print(np.sqrt(arr2))

[[ 8.1240384  26.01922366  9.11043358  9.53939201  9.64365076]
 [ 1.73205081 14.89966443  5.83095189  8.1240384   1.41421356]]
[[2.         2.23606798 2.64575131 2.82842712 1.41421356]
 [4.69041576 5.91607978 8.1240384  6.63324958 4.79583152]]


In [76]:
#arthmetic operations on 3D array

In [84]:
#addition
arr1=np.array([[[1,22,3,4,212],[2,3,5,7,8]],
               [[12,122,3,44,5],[32,44,5,32,2]],
               [[23,4,55,22,4],[23,33,55,22,90]]])
arr2=np.array([[[33,4,55,6,777],[73,3,4,5,66]],
               [[33,22,3,56,8],[4,66,78,2,44]],
               [[43,55,77,333,5],[4,45,7,8,3]]])
print(arr1+arr2)
np.add(arr1,arr2)

[[[ 34  26  58  10 989]
  [ 75   6   9  12  74]]

 [[ 45 144   6 100  13]
  [ 36 110  83  34  46]]

 [[ 66  59 132 355   9]
  [ 27  78  62  30  93]]]


array([[[ 34,  26,  58,  10, 989],
        [ 75,   6,   9,  12,  74]],

       [[ 45, 144,   6, 100,  13],
        [ 36, 110,  83,  34,  46]],

       [[ 66,  59, 132, 355,   9],
        [ 27,  78,  62,  30,  93]]])

In [86]:
#subtraction
arr1=np.array([[[1,22,3,4,212],[2,3,5,7,8]],
               [[12,122,3,44,5],[32,44,5,32,2]],
               [[23,4,55,22,4],[23,33,55,22,90]]])
arr2=np.array([[[33,4,55,6,777],[73,3,4,5,66]],
               [[33,22,3,56,8],[4,66,78,2,44]],
               [[43,55,77,333,5],[4,45,7,8,3]]])
print(arr1-arr2)
np.subtract(arr1,arr2)

[[[ -32   18  -52   -2 -565]
  [ -71    0    1    2  -58]]

 [[ -21  100    0  -12   -3]
  [  28  -22  -73   30  -42]]

 [[ -20  -51  -22 -311   -1]
  [  19  -12   48   14   87]]]


array([[[ -32,   18,  -52,   -2, -565],
        [ -71,    0,    1,    2,  -58]],

       [[ -21,  100,    0,  -12,   -3],
        [  28,  -22,  -73,   30,  -42]],

       [[ -20,  -51,  -22, -311,   -1],
        [  19,  -12,   48,   14,   87]]])

In [92]:
#multiplication
arr1=np.array([[[2,3,4,56,6],[23,4,5,2,4]],
               [[23,23,55,33,4],[34,43,44,32,2]]])
n=4
arr2=np.array([[[2,33,4,5,6],[2,23,5,0,5]],
               [[2,23,44,2,1],[12,34,2,3,1]]])
print(arr1*arr2)
print(arr1*n)
print(n*arr2)
print(np.multiply(arr1,arr2))

[[[   4   99   16  280   36]
  [  46   92   25    0   20]]

 [[  46  529 2420   66    4]
  [ 408 1462   88   96    2]]]
[[[  8  12  16 224  24]
  [ 92  16  20   8  16]]

 [[ 92  92 220 132  16]
  [136 172 176 128   8]]]
[[[  8 132  16  20  24]
  [  8  92  20   0  20]]

 [[  8  92 176   8   4]
  [ 48 136   8  12   4]]]
[[[   4   99   16  280   36]
  [  46   92   25    0   20]]

 [[  46  529 2420   66    4]
  [ 408 1462   88   96    2]]]


In [94]:
#division
arr1=np.array([[[22,33,44,56,66],[8,3,1,2,22]],
               [[3,23,3,4,5],[9,8,5,9,3]]])
arr2=np.array([[[2,33,4,5,6],[73,2,3,4,5]],
               [[3,45,62,3,4],[4,6,7,2,9]]])
n=10
print(arr1/arr2)
print(arr1/n)
print(n/arr2)
print(np.divide(arr1,arr2))

[[[11.          1.         11.         11.2        11.        ]
  [ 0.10958904  1.5         0.33333333  0.5         4.4       ]]

 [[ 1.          0.51111111  0.0483871   1.33333333  1.25      ]
  [ 2.25        1.33333333  0.71428571  4.5         0.33333333]]]
[[[2.2 3.3 4.4 5.6 6.6]
  [0.8 0.3 0.1 0.2 2.2]]

 [[0.3 2.3 0.3 0.4 0.5]
  [0.9 0.8 0.5 0.9 0.3]]]
[[[5.         0.3030303  2.5        2.         1.66666667]
  [0.1369863  5.         3.33333333 2.5        2.        ]]

 [[3.33333333 0.22222222 0.16129032 3.33333333 2.5       ]
  [2.5        1.66666667 1.42857143 5.         1.11111111]]]
[[[11.          1.         11.         11.2        11.        ]
  [ 0.10958904  1.5         0.33333333  0.5         4.4       ]]

 [[ 1.          0.51111111  0.0483871   1.33333333  1.25      ]
  [ 2.25        1.33333333  0.71428571  4.5         0.33333333]]]


In [96]:
#floor division
arr1=np.array([[[22,33,44,56,66],[23,4,55,7,30]],
               [[4,32,1,3,5],[4,64,2,4,1]]])
arr2=np.array([[[2,33,4,5,6],[3,1,1,3,5]],
               [[4,3,1,6,8],[7,2,3,7,9]]])
n=11
print(arr1//arr2)
print(arr1//n)
print(n//arr2)
print(np.floor_divide(arr1,arr2))

[[[11  1 11 11 11]
  [ 7  4 55  2  6]]

 [[ 1 10  1  0  0]
  [ 0 32  0  0  0]]]
[[[2 3 4 5 6]
  [2 0 5 0 2]]

 [[0 2 0 0 0]
  [0 5 0 0 0]]]
[[[ 5  0  2  2  1]
  [ 3 11 11  3  2]]

 [[ 2  3 11  1  1]
  [ 1  5  3  1  1]]]
[[[11  1 11 11 11]
  [ 7  4 55  2  6]]

 [[ 1 10  1  0  0]
  [ 0 32  0  0  0]]]


In [98]:
#modulus
arr1=np.array([[[1,22,3,4,5],[6,3,2,3,4]],
               [[4,6,2,9,2],[4,9,2,1,7]]])
arr2=np.array([[[2,4,5,6,6],[3,2,4,6,77]],
               [[4,1,5,6,1],[6,9,2,6,8]]])
n=6
print(arr1%arr2)
print(arr1%n)
print(n%arr2)
print(np.mod(arr1,arr2))

[[[1 2 3 4 5]
  [0 1 2 3 4]]

 [[0 0 2 3 0]
  [4 0 0 1 7]]]
[[[1 4 3 4 5]
  [0 3 2 3 4]]

 [[4 0 2 3 2]
  [4 3 2 1 1]]]
[[[0 2 1 0 0]
  [0 0 2 0 6]]

 [[2 0 1 0 0]
  [0 6 0 0 6]]]
[[[1 2 3 4 5]
  [0 1 2 3 4]]

 [[0 0 2 3 0]
  [4 0 0 1 7]]]


In [102]:
#square root
arr1=np.array([[[66,677,83,91,93],[3,222,34,66,2]],
               [[4,2,22,4,55],[44,88,2,33,22]]])
arr2=np.array([[[4,5,7,8,2],[22,35,66,44,23]],
               [[44,3,112,45,3334],[34,563,98,74,78]]])
print(np.sqrt(arr1))
print(np.sqrt(arr2))

[[[ 8.1240384  26.01922366  9.11043358  9.53939201  9.64365076]
  [ 1.73205081 14.89966443  5.83095189  8.1240384   1.41421356]]

 [[ 2.          1.41421356  4.69041576  2.          7.41619849]
  [ 6.63324958  9.38083152  1.41421356  5.74456265  4.69041576]]]
[[[ 2.          2.23606798  2.64575131  2.82842712  1.41421356]
  [ 4.69041576  5.91607978  8.1240384   6.63324958  4.79583152]]

 [[ 6.63324958  1.73205081 10.58300524  6.70820393 57.74080013]
  [ 5.83095189 23.72762104  9.89949494  8.60232527  8.83176087]]]
