In [1]:
#Numpy
!pip install numpy

In [3]:
#importing numpy
import numpy as np

In [27]:
#creating numpy
a=np.array([1,2,3,4])
b=np.array([(5,6,7,8),(9,8,10,11)],dtype=float)
c=np.array([[(1.5,8.9,10,0),(1,2,33,4)],[(11.1,22,2,1),(2,33,21,1)]],dtype=float)
print(a)
print(b)
print(c)

[1 2 3 4]
[[ 5.  6.  7.  8.]
 [ 9.  8. 10. 11.]]
[[[ 1.5  8.9 10.   0. ]
  [ 1.   2.  33.   4. ]]

 [[11.1 22.   2.   1. ]
  [ 2.  33.  21.   1. ]]]


In [ ]:
#Initial placeholders 

In [47]:
#creating an array of zeros
np.zeros((10,5))#rows & colomns

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [45]:
#creating an array of one's
np.ones((2,4,2))#shape(depth),rows,colomns

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [57]:
#creating an array of values with same differene
d=np.arange(0,25,5)
print(d)

[ 0  5 10 15 20]


In [63]:
#creating an array with evenly spaced values with same difference
np.linspace(0,10,30)

array([ 0.        ,  0.34482759,  0.68965517,  1.03448276,  1.37931034,
        1.72413793,  2.06896552,  2.4137931 ,  2.75862069,  3.10344828,
        3.44827586,  3.79310345,  4.13793103,  4.48275862,  4.82758621,
        5.17241379,  5.51724138,  5.86206897,  6.20689655,  6.55172414,
        6.89655172,  7.24137931,  7.5862069 ,  7.93103448,  8.27586207,
        8.62068966,  8.96551724,  9.31034483,  9.65517241, 10.        ])

In [73]:
#creating a 1D array with same values
e=np.full((5),100)
print(e)

[100 100 100 100 100]


In [81]:
#creating a 2D array with same values and printing dimensions
f=np.full((3,4),100)
print(f)
print(f.ndim)

[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]]
2


In [87]:
#creating a 2D array with same values and printing dimensions
g=np.full((3,4,5),100)
print(g)
print(g.ndim)

[[[100 100 100 100 100]
  [100 100 100 100 100]
  [100 100 100 100 100]
  [100 100 100 100 100]]

 [[100 100 100 100 100]
  [100 100 100 100 100]
  [100 100 100 100 100]
  [100 100 100 100 100]]

 [[100 100 100 100 100]
  [100 100 100 100 100]
  [100 100 100 100 100]
  [100 100 100 100 100]]]
3


In [103]:
#creating an nXn identity matrix
h=np.eye(4)
print(h)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [105]:
#creating an array with random values(between 0 and 1 only)
np.random.random((2,3))

array([[0.27111715, 0.72203792, 0.52759372],
       [0.85512246, 0.46567742, 0.99631064]])

In [123]:
#to find dimensions of matrix
arr=np.array([[1,2,3,4,5],
              [2,3,4,5,6],
              [3,4,5,6,7]])
#print(np.shape(arr))
arr.shape

(3, 5)


(3, 5)

In [125]:
#to find no.of elements in an array
arr=np.array([[1,2,3,4,5],
              [2,3,4,5,6],
              [3,4,5,6,7]])
print(arr.size)

15


In [127]:
#to find length of array 
arr=np.array([[1,2,3,4,5],
              [2,3,4,5,6],
              [3,4,5,6,7]])
len(arr)

3