In [1]:
#Numpy
!pip install numpy

In [1]:
#importing numpy
import numpy as np

In [27]:
#creating numpy
a=np.array([1,2,3,4])
b=np.array([(5,6,7,8),(9,8,10,11)],dtype=float)
c=np.array([[(1.5,8.9,10,0),(1,2,33,4)],[(11.1,22,2,1),(2,33,21,1)]],dtype=float)
print(a)
print(b)
print(c)

[1 2 3 4]
[[ 5.  6.  7.  8.]
 [ 9.  8. 10. 11.]]
[[[ 1.5  8.9 10.   0. ]
  [ 1.   2.  33.   4. ]]

 [[11.1 22.   2.   1. ]
  [ 2.  33.  21.   1. ]]]


In [ ]:
#Initial placeholders 

In [47]:
#creating an array of zeros
np.zeros((10,5))#rows & colomns

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [45]:
#creating an array of one's
np.ones((2,4,2))#shape(depth),rows,colomns

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [57]:
#creating an array of values with same differene
d=np.arange(0,25,5)
print(d)

[ 0  5 10 15 20]


In [63]:
#creating an array with evenly spaced values with same difference
np.linspace(0,10,30)

array([ 0.        ,  0.34482759,  0.68965517,  1.03448276,  1.37931034,
        1.72413793,  2.06896552,  2.4137931 ,  2.75862069,  3.10344828,
        3.44827586,  3.79310345,  4.13793103,  4.48275862,  4.82758621,
        5.17241379,  5.51724138,  5.86206897,  6.20689655,  6.55172414,
        6.89655172,  7.24137931,  7.5862069 ,  7.93103448,  8.27586207,
        8.62068966,  8.96551724,  9.31034483,  9.65517241, 10.        ])

In [73]:
#creating a 1D array with same values
e=np.full((5),100)
print(e)

[100 100 100 100 100]


In [81]:
#creating a 2D array with same values and printing dimensions
f=np.full((3,4),100)
print(f)
print(f.ndim)

[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]]
2


In [87]:
#creating a 2D array with same values and printing dimensions
g=np.full((3,4,5),100)
print(g)
print(g.ndim)

[[[100 100 100 100 100]
  [100 100 100 100 100]
  [100 100 100 100 100]
  [100 100 100 100 100]]

 [[100 100 100 100 100]
  [100 100 100 100 100]
  [100 100 100 100 100]
  [100 100 100 100 100]]

 [[100 100 100 100 100]
  [100 100 100 100 100]
  [100 100 100 100 100]
  [100 100 100 100 100]]]
3


In [103]:
#creating an nXn identity matrix
h=np.eye(4)
print(h)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [105]:
#creating an array with random values(between 0 and 1 only)
np.random.random((2,3))

array([[0.27111715, 0.72203792, 0.52759372],
       [0.85512246, 0.46567742, 0.99631064]])

In [123]:
#to find dimensions of matrix
arr=np.array([[1,2,3,4,5],
              [2,3,4,5,6],
              [3,4,5,6,7]])
#print(np.shape(arr))
arr.shape

(3, 5)


(3, 5)

In [125]:
#to find no.of elements in an array
arr=np.array([[1,2,3,4,5],
              [2,3,4,5,6],
              [3,4,5,6,7]])
print(arr.size)

15


In [3]:
#to find length of array 
arr=np.array([[1,2,3,4,5],
              [2,3,4,5,6],
              [3,4,5,6,7]])
len(arr)

3

In [11]:
#accessing array elements
#we can access the elements using the index values
arr=np.array([1,2,3,5,6,677])
print(arr[1])
print(arr[4])
print(*arr[1:4])

2
6
2 3 5


In [33]:
#adding two index positions
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([7.8,8,33,4,55,66])
x=arr1[3]+arr2[3]
print(x)
np.dtype(x)

8.0


dtype('float64')

In [63]:
#accessing elements in 2D array
arr=np.array([[1,2,3,4,5],[6,7,8,9,0],[1,2,3,4,5],[6,7,8,9,0]])
print(arr[1,3])
print(arr[0,2])
print(arr[3,2])

9
3
8


In [89]:
#accessing elements in 3D array
arr=np.array([[[1,2,3,4,5],
               [6,7,8,9,0],
               [1,2,3,4,5],
               [6,7,8,9,0]],
              [[1,2,3,4,5],
               [6,7,8,9,0],
               [1,2,3,4,5],
               [6,7,8,9,0]],
              [[1,2,3,4,5],
               [6,7,8,9,0],
               [1,2,3,4,5],
               [6,7,8,9,0]]]
              )
print(arr[1,1,3])
print(arr[0,0,0])
print(arr[2,1,4])

9
1
0


In [97]:
#data types in numpy
'''
i--integer
b--boolean
u--unsigned integer
f--float
c--complex float
M--date and time
O--object
S--string
'''
#string
arr=np.array([1,2,3,4],dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [121]:
#integer
arr=np.array([1,2,33,4,5.5,55.55,1111111111],dtype='i')
print(arr)
print(arr.dtype)

[         1          2         33          4          5         55
 1111111111]
int32


In [127]:
#changing float to int
arr=np.array([1.1,2.2,3.3,4,5.5])
new_arr=arr.astype('i')
print(new_arr)

[1 2 3 4 5]


In [129]:
#changing float to boolean
arr=np.array([0.0,1.1,2.2,3.3,4,5.5])
x=arr.astype(bool)
print(x)

[False  True  True  True  True  True]


In [131]:
#changing int to float
arr=np.array([0,1,2,3,4,5])
x=arr.astype('f')
print(x)

[0. 1. 2. 3. 4. 5.]


In [135]:
#changing float to unsigned integer
arr=np.array([1.1,2.2,3.3,4,5.5])
new_arr=arr.astype('U')
print(new_arr)

['1.1' '2.2' '3.3' '4.0' '5.5']


In [137]:
#changing int to unsigned integer
arr=np.array([1,2,3,4,5])
new_arr=arr.astype('U')
print(new_arr)

['1' '2' '3' '4' '5']


In [143]:
#changing float to complex float
arr=np.array([1.1,2.2,3.3,4,5.5])
new_arr=arr.astype('c')
print(new_arr)

[b'1' b'2' b'3' b'4' b'5']


In [145]:
#changing int to complex float
arr=np.array([1,2,3,4,5])
new_arr=arr.astype('c')
print(new_arr)

[b'1' b'2' b'3' b'4' b'5']


In [149]:
#copy method
arr=np.array([21,221,212,12112,122121])
temp=arr.copy()
arr[0]=2
temp[0]=0
print(temp)

[     0    221    212  12112 122121]


In [155]:
#view method
arr=np.array([21,221,212,12112,122121])
temp=arr.view()
arr[0]=2
print(temp)

[     2    221    212  12112 122121]


In [177]:
#Reshaping arrays
#reshaping means chaning the shape of an array
#converting 1D array to 2D array
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18])
x=arr.reshape(3,6)
y=arr.reshape(9,2)
print(x)
print("--------------------")
print(y)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]
--------------------
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]]


In [189]:
#converting 1D array into 3D array
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
x=arr.reshape(2,2,5)
print(x)
print("---------------------")
y=arr.reshape(5,2,2)
print(y)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]
---------------------
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]

 [[17 18]
  [19 20]]]


In [205]:
#converting 2D array into 1D array
arr=np.array([[1,2,3,4,5,6],
              [7,8,9,10,11,12],
              [13,14,15,16,17,18]])
x=arr.reshape(arr.size)
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


In [215]:
#converting 2D array into 3D array
arr=np.array([[1,2,3,4,5,6],
              [7,8,9,10,11,12],
              [13,14,15,16,17,18]])
print(arr.size)
x=arr.reshape(3,2,3)
print(x)
print("----------------------")
y=arr.reshape(2,3,3)
print(y)
print("----------------------")
z=arr.reshape(3,3,2)
print(z)

18
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
----------------------
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
----------------------
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]]


In [217]:
#converting 3D array into 1D array
arr=np.array([[[1,2,3,4,5,6],[7,8,9,10,11,12]],
              [[13,14,15,16,17,18],[19,20,21,22,23,24]],
              [[25,26,27,28,29,30],[31,32,33,34,35,36]]])
x=arr.reshape(arr.size)
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36]


In [229]:
#converting 3D array into 2D array
arr=np.array([[[1,2,3,4,5,6],[7,8,9,10,11,12]],
              [[13,14,15,16,17,18],[19,20,21,22,23,24]],
              [[25,26,27,28,29,30],[31,32,33,34,35,36]]])
print(arr.size)
x=arr.reshape(6,6)
print(x)
print("---------------------------------------------------")
y=arr.reshape(2,18)
print(y)
print("---------------------------------------------------")
z=arr.reshape(3,12)
print(z)
print("---------------------------------------------------")
a=arr.reshape(4,9)
print(a)

36
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
---------------------------------------------------
[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
 [19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36]]
---------------------------------------------------
[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32 33 34 35 36]]
---------------------------------------------------
[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]
 [19 20 21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34 35 36]]


In [252]:
#sorting arrays
arr=np.array([5,2,55,2,102,12])
x=np.sort(arr)
print(x)

[  2   2   5  12  55 102]


In [258]:
#slicing arrays
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
#positive slicing
print(arr[2:18])
#negative slicing
print(arr[-16:-3])

[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
[ 5  6  7  8  9 10 11 12 13 14 15 16 17]


In [270]:
#slicing 2D arrays
arr=np.array([[1,2,3,4,5,6],
              [7,8,9,10,11,12],
              [13,14,15,16,17,18]])
print(arr[0,1:4])
print("----------")
print(arr[0:2,3:5])
print("----------")
print(arr[:,:])

[2 3 4]
----------
[[ 4  5]
 [10 11]]
----------
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]


In [284]:
#slicing 3D arrays
arr=np.array([[[1,2,3,4,5,6],[7,8,9,10,11,12]],
              [[13,14,15,16,17,18],[19,20,21,22,23,24]],
              [[25,26,27,28,29,30],[31,32,33,34,35,36]]])
print(arr[0,0,1:4])
print("----------")
print(arr[0,0:2,3:5])
print("----------")
print(arr[:,:,:])

[2 3 4]
----------
[[ 4  5]
 [10 11]]
----------
[[[ 1  2  3  4  5  6]
  [ 7  8  9 10 11 12]]

 [[13 14 15 16 17 18]
  [19 20 21 22 23 24]]

 [[25 26 27 28 29 30]
  [31 32 33 34 35 36]]]
